# Generated by Django 4.2.16 on 2024-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_remove_contact_created_at_contact_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_time',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
