# Generated by Django 4.2.16 on 2024-12-02 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0004_remove_contact_created_at_contact_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_time',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
